[package]
name = "pi-generator-from-random-numbers"
version = "2.0.2"
authors = ["Jake Vossen <jake@vossen.dev>"]
edition = "2018"

[dependencies]
rand = "0.8.3"
num = "0.3.1"
[[bin]]
name = "pi-generator-from-random-numbers"
