[package]
name = "pi-generator-from-random-numbers"
version = "2.0.2"
authors = ["Jake Vossen <jake@vossen.dev>"]
edition = "2018"

[dependencies]
rand = "0.7.2"
num = "0.2.0"
[[bin]]
name = "pi-generator-from-random-numbers"
path = "main.rs"
